### ISSUE TITLE
SSH timeout on new install

### ISSUE THREAD

**Issue by thewildofficial** [DeadPackets/pwnbox-cli#6]
installed a new version of docker and reinstalled pwnbox, when I tried running the command `pwnbox up`, I was met by the prompt `Waiting for SSH to be available...`, and then finally it throws
`Error: Timeout waiting for SSH to available in PwnBox.`

Host Environment Details:
OpenSSH_8.1p1, LibreSSL 2.7.3
Python 2.7.16
Docker version 20.10.11, build dea9396

**Comment by DeadPackets** [comment]
This turned out to be an error due to not having any generated SSH keys, but the CLI should detect that for new users. Will add an error check.
